name: Second Deploy website Artifacts
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
#This job creates a job artifact - some files
#To store locally files that are produced by a build job, we need to add this step action - upload artifacts.
#We add a name to artifact - dist-files, a path to describe where to find all files (artifacts) that are created.
#Thanks to this step, we store all files (artifacts) in a dist-files folder that were found
#They are located in a workflow. We can download it (access manually)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
#In this step, we download artifacts from a job build. It is clear that it must run after a job build is completed successfully
    needs: build
    runs-on: ubuntu-latest
    steps:
#Each job runs in another runner machines. To hold artifacts created by a build job, we need to download these artifacts. 
#We need to specify a folder that will be downloaded. Thus, this files will be available in a deploy job
      - name: Get build artifacts
        uses: actions/download-artifacts@v4
        with:
          name: dist-files 
      - name: Output contents. List of all folders that are available in 
        run: ls
      - name: Deploy
        run: echo "Deploying..."

#After running a build job, it will produce files.
#We can take a look at these files locally by running commands on the terminal:
#npm install
#npm run build
#It produces a dist folder.It is the artifact produced by a build job in GitHub Action.
#This folder should be uploaded to some web server
#It is the output of this build step (a build job)
#If we run this workflow on GitHub Actions - these files are produced on the runner machine
#If the workflow is finished, the runner machine will be shutdown - these files will be lost
#Therefore, we want to store these files locally after the runner machine will be shut down